### ISSUE TITLE
moonbeam.png is HUGE

### ISSUE THREAD

**Issue by fl0wo** [ErikThiart/cryptocurrency-icons#10]
**Is your feature request related to a problem? Please describe.**

This icon 3200x3200 and not 32x32
https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/moonbeam.png

**Describe the solution you'd like**

That icon to be 32x32

**Describe alternatives you've considered**

We could consider to instead buy a 100x bigger monitor.

**Additional context**

I cant add a screenshot as the png cant fit

**Comment by ErikThiart** [comment]
Shit. Sorry about that.

**Comment by ErikThiart** [comment]
I think it is removed now, will re add correct size.

**Comment by ErikThiart** [comment]
Dammit, seems something is odd on that one.
