### ISSUE TITLE
Higher quality

### ISSUE THREAD

**Issue by michaeltieso** [ErikThiart/cryptocurrency-icons#2]
Would you by chance have larger icons? It's be great to separate them by size. 32x32, 64x64, 128x128, etc.

**Comment by ErikThiart** [comment]
Unfortunately I'm only able to source 32x32 size cryptocurreincy icons atm. 

I manually scavenge sites and collect them one by one.

**Comment by michaeltieso** [comment]
whoa @ErikThiart
