### ISSUE TITLE
No mapping available

### ISSUE THREAD

**Issue by saqibsoftwares** [ErikThiart/cryptocurrency-icons#3]
Hi,
Is there any symbol<-->name mapping available for these icons? I have to enter the currency names manually for all the thousands of currencies icon which is not possible.

**Comment by ErikThiart** [comment]
I hope this helps, the file name is a slug of the coin name

`/github/cryptocurrency-icons/64/'.$coin['slug'].'.png'`

so Bitcoin will be bitcoin.png and Advanced Internet Blocks (AIB) will be advanced-internet-blocks.png

**Comment by saqibsoftwares** [comment]
Actually I'm using binance API and binance does not support or provides coin names such as bitcoin, Fantom etc. They only provide symbols i.e. BTC or FTM. There is no way to resolve symbol into coin name or slug (BTC to bitcoin or FTM to fantom) It would be great if all those icons available with symbol file name such as btc.png or luna.png etc.

Another issue is, I have used your icons in one of my project then after few days I have to remove tham the reason is list is many icons are wrong (i.e. matic and luna) and many famous crypto icons are missing.

**Comment by ErikThiart** [comment]
Famous coins won't be missing, ie top 2000 coins are there, give some examples then I can manually look into it.

Got it RE the mapping, I will work on something to make it more compatible.

**Comment by ErikThiart** [comment]
Map added

`
{
"name": "NanoMeter Bitcoin",
"symbol": "NMBTC",
"slug": "nanometer-bitcoin",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/nanometer-bitcoin.png"
},
{
"name": "XXT-Token",
"symbol": "XXT",
"slug": "xxt-token",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/xxt-token.png"
},
{
"name": "DEUS Finance",
"symbol": "DEUS",
"slug": "deus-finance-2",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/deus-finance-2.png"
},
{
"name": "Adventure Token",
"symbol": "TWA",
"slug": "adventure-token",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/adventure-token.png"
},
{
"name": "SaltSwap Finance",
"symbol": "SALT",
"slug": "saltswap-finance",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/saltswap-finance.png"
},
{
"name": "Pomicoin",
"symbol": "POMI",
"slug": "pomicoin",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/pomicoin.png"
},
{
"name": "Nucleus",
"symbol": "NUCLEUS",
"slug": "nucleus",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/nucleus.png"
},
{
"name": "Etherprint",
"symbol": "ETHP",
"slug": "etherprint",
"img_url": "https://raw.githubusercontent.com/ErikThiart/cryptocurrency-icons/master/32/etherprint.png"
},
`
